### ISSUE TITLE
[Feedback] Page: /install/latest/self-hosted/installation-debian/

### ISSUE THREAD

**Issue by thehatami** [timescale/docs#1746] opened 2022-11-07 18:53 UTC
### Is it easy to find the information you need?

No

### Are the instructions clear?

No

### How could we improve the Timescale documentation site?

by this command
```
wget --quiet -O - https://packagecloud.io/timescale/timescaledb/gpgkey | sudo apt-key add -
```
 we get these error:
```
gpg: no valid OpenPGP data found.
```

os: ubuntu 20.04 focal

**Comment by Rajakavitha1** [comment] 2022-11-11 05:31
Hi @thehatami !!! I tried to reproduce the issue on ubuntu 20.04 and It works for me:
```
rajie@postgresql:~$ sudo wget --quiet -O - https://packagecloud.io/timescale/timescaledb/gpgkey | sudo apt-key add -
OK
rajie@postgresql:~$ sudo apt update
```

**Comment by Rajakavitha1** [comment] 2022-11-11 05:32
Closing this issue for now. Please feel free to reopen if any other updates need to be made.

**Closed by Rajakavitha1** 2022-11-11 05:32 UTC
Labels: documentation, community, feedback
