### ISSUE TITLE
[Enhancement]: Document enable_chunk_skipping

### ISSUE THREAD

**Issue by abbudao** [timescale/docs#3373] opened 2024-08-07 14:13 UTC
### What type of enhancement is this?

Other

### What subsystems and features will be improved?

Other

### What does the enhancement do?

The newly supported optimization `enable_chunk_skipping` should be documented. Examples in which cases it should be used would also be very welcome.

**Comment by atovpeko** [comment] 2024-09-20 07:17
Closing as duplicate of https://github.com/timescale/docs/issues/3424

**Closed as completed by atovpeko** 2024-09-20 07:17 UTC
Labels: enhancement
