### ISSUE TITLE
[Site Bug] Timescale Toolkit is now available in the RPM & deb repos [Issue with the page: /timescaledb/latest/how-to-guides/hyperfunctions/install-toolkit/]

### ISSUE THREAD

**Issue by nmaludy** [timescale/docs#822] opened 2022-02-16 19:55 UTC
# Describe the bug

Looks like timescale-toolkit is available in RPM+DEB repos now, should add that to the docs.  Similar probably here: https://github.com/timescale/timescaledb-toolkit in the main README.

## What do the docs say now?

They tell you how to build the toolkit from source.

## What should the docs say?

Add information about installing from RPM+DEB using packagecloud repo.

# Page affected
https://docs.timescale.com/timescaledb/latest/how-to-guides/hyperfunctions/install-toolkit/#installing-toolkit-on-self-hosted-timescaledb

# Version affected
latest

**Comment by Loquacity** [comment] 2022-02-17 05:16
Duplicate of https://github.com/timescale/docs/issues/541

**Closed by Loquacity** 2022-02-17 05:16 UTC
Labels: bug, documentation
