### ISSUE TITLE
[Site Bug] Issue with the page: /timescaledb/latest/how-to-guides/distributed-hypertables/

### ISSUE THREAD

**Issue by ericcoulthard** [timescale/docs#210] opened 2021-07-26 15:58 UTC
_Use this template for reporting bugs in the docs._

# Describe the bug

Broken Link.
https://docs.timescale.com/overview/limitations/#distributed-hypertable-limitations

## What do the docs say now?

Distributed hypertables currently have some limitations when compared to non-distributed hypertables. Before creating a distributed hypertable for production workloads, please review our limitations document to ensure that your use case will work as expected. You can also contact us or join the #multinode channel in our community Slack.

## What should the docs say?

Should probably say the same thing. The link should be fixed though.

# Page affected

https://docs.timescale.com/timescaledb/latest/how-to-guides/distributed-hypertables/##distributed-hypertables

# Version affected

latest v2.X

# Screenshots

![image](https://user-images.githubusercontent.com/46009938/127020677-9bc3c52a-c276-4343-99fb-054ab6b04249.png)

**Comment by Loquacity** [comment] 2021-07-27 00:29
Duplicate of https://github.com/timescale/docs/issues/204

**Closed by Loquacity** 2021-07-27 00:29 UTC
Labels: bug, documentation
