### ISSUE TITLE
[Feedback] Clarify advice for setting compression

### ISSUE THREAD

**Issue by Rajakavitha1** [timescale/docs#1952] opened 2023-01-16 12:52 UTC
### Is it easy to find the information you need?

Yes

### Are the instructions clear?

Yes

### How could we improve the Timescale documentation site?

https://docs.timescale.com/timescaledb/latest/how-to-guides/compression/about-compression/#segment-by-columns

```I'm trying to figure out what settings I should use for compression. The docs mention that segments should contain at least 100 rows per chunk, but there is no mention of an upper limit. Is there a suggested upper limit, or is it strictly the more, the better?```

Related blogs that have the information: https://www.timescale.com/blog/timescale-cloud-tips-testing-your-chunk-size/amp/ and https://www.timescale.com/forum/t/choosing-the-right-chunk-time-interval-value-for-timescaledb-hypertables/116

[slack message](https://timescaledb.slack.com/archives/C4GT3N90X/p1673865956172619?thread_ts=1673865956.172619&cid=C4GT3N90X)

**Comment by Loquacity** [comment] 2023-02-08 04:03
From what I can see, the content already points to the blog post, and the blog post itself is far too lengthy to reproduce in full in the How To, and I can't see any short and sharp bits that are worth reproducing. I see that the OP wanted info about the compression maximums, but it's all very reliant on what the individual user's data looks like, and for that, you really need the entire post. Closing WONTFIX for now.

**Closed by Loquacity** 2023-02-08 04:03 UTC
Labels: documentation, community, feedback
