### ISSUE TITLE
[Docs RFC] Add Cloud regions

### ISSUE THREAD

**Issue by charislam** [timescale/docs#775] opened 2022-02-04 17:45 UTC
# Describe change in content, appearance, or functionality

Docs mention [MST regions](https://docs.timescale.com/timescaledb/latest/overview/faq/faq-products/#is-timescaledb-currently-being-used-in-production) but not cloud regions. Add cloud regions.

# Subject matter expert (SME)

[If known, who is a good person to ask about this topic]

# Deadline

[When does this need to be addressed]

# Any further info

[Anything else you want to add, or further links]

**Comment by Loquacity** [comment] 2022-03-10 05:20
Duplicate of https://github.com/timescale/docs-private/issues/23

**Closed by Loquacity** 2022-03-10 05:20 UTC
Labels: documentation, enhancement
