### ISSUE TITLE
[Docs RFC] Add info about dropping metric data by series ID

### ISSUE THREAD

**Issue by Loquacity** [timescale/docs#844] opened 2022-02-21 01:07 UTC
# Describe change in content, appearance, or functionality

> I had some misconfiguration in my Prometheus that caused I ended up with many series duplicates ("multiplicates", in fact, I have 5 copies of every serie for some time). Now and I need to drop all series having a specific label name only. How do I do that? Existence of a specific label is the only criterior for dropping and I need to drop all series from all metrics having this particular label (called "__database__") present. How do I do it? Thank you.

> hey, you can drop the series by series ID from a particular metric by using
> _prom_catalog.delete_series_from_metric(name text, series_ids bigint[])
> this means you have to do this for each metric you have and each series ID that contains that particular label
> that's the best solution i can think of

# Subject matter expert (SME)

@antekresic 

# Deadline

[When does this need to be addressed]

# Any further info

Link to Community Slack thread: https://timescaledb.slack.com/archives/C011FC0PPC5/p1645168130769889

**Comment by Rajakavitha1** [comment] 2022-03-24 13:48
Hi @Loquacity  and @charislam Looks like this issue is a duplicate of issue [#837](https://github.com/timescale/docs/issues/837) that was logged on Feb 18.  Closing this issue for now. Please feel free to reopen if  any other changes need to be made.

**Closed by Rajakavitha1** 2022-03-24 13:48 UTC
Labels: documentation, enhancement, community
