### ISSUE TITLE
[Site Bug] Issue with the page: /timescaledb/latest/how-to-guides/hypertables/create/

### ISSUE THREAD

**Issue by CliveDent** [timescale/docs#636] opened 2021-12-02 13:01 UTC
Starting with timescaledb, here is what already confused me:

1) There is  `CREATE TABLE TABLE_NAME ...` as an example query and right below is `SELECT create_hypertable('conditions', ...` while there is no explanation for where did the 'conditions' come from. Same with the next example.

2) Link to `create_hypertable()` function documentation is missing. Also, the same example is used there but without table definition that is at this page.

Thank you.

**Comment by Rajakavitha1** [comment] 2021-12-09 10:21
Hi @Loquacity Please let me know if the PR [ ](https://github.com/timescale/docs/pull/643) addresses the issues mentioned in this issue.

**Comment by Rajakavitha1** [comment] 2021-12-10 04:26
> > Hi @Loquacity Please let me know if the PR [ ](https://github.com/timescale/docs/pull/643) addresses the issues mentioned in this issue.
> 
> Which PR?

Here's the PR: [ ](https://github.com/timescale/docs/pull/643)

**Comment by Loquacity** [comment] 2021-12-10 05:57
> > > Hi @Loquacity Please let me know if the PR [ ](https://github.com/timescale/docs/pull/643) addresses the issues mentioned in this issue.
> > 
> > 
> > Which PR?
> 
> Here's the PR: #643

That PR only addresses point 1, from what I can see ... ?

**Comment by Loquacity** [comment] 2021-12-13 05:22
Closed as duplicate of https://github.com/timescale/docs/issues/642

**Closed by Loquacity** 2021-12-13 05:22 UTC
Labels: bug, documentation, community
